language: ruby
rvm:
  - 2.0.0

before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database fora_test;' -U postgres
  - rake db:migrate
  - export RUBY_GC_MALLOC_LIMIT=50000000

bundler_args: --without development

script: xvfb-run rake

notifications:
  email: false

services:
  - redis-server
