language: ruby
rvm:
  - 2.0.0

before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database fora_test;' -U postgres
  - rake db:migrate
  - export RUBY_GC_MALLOC_LIMIT=50000000

bundler_args: --without development production

script: xvfb-run rake

notifications:
  email: false

addons:
  code_climate:
    repo_token: 85d9258a24758e9dd5ed205063cf141c06e9af368194afcfd719440794ab227b
