language: ruby
rvm:
  - 2.0.0

before_script:
  - echo '--color' > .rspec
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database fora_test;' -U postgres
  - rake db:migrate
  - export RUBY_GC_MALLOC_LIMIT=50000000

bundler_args: --without development
script: xvfb-run rake

notifications:
  email: false

services:
  - redis-server

deploy:
  provider: heroku
  api_key:
    secure: KBUFp9rea2ve21bXvPxox3nIr2NHz/EOhB7kLaPNysPzYq9jVuXbPRZ2SMj3ReyZyZrwUKuaVUqGR0Bn+yNS+w+Xe5tA5uBI2WOvw+s7cM3GrZNAcNYJWbnJAqZgWHLAV7w2PLwoCF2LaiZYgKOApOYtkOIgKNXSSVT3CtAiLTg=
  app: fora
  on:
    repo: toctan/fora
